CREATE DATABASE beyond_quantum;

USE beyond_quantum;

CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id CHAR(6) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    username VARCHAR(100) NOT NULL UNIQUE,
    phone VARCHAR(20) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
);
